import { Post } from "@/types/post";

export const posts: Post[] = [
  { id: "p1", title: "Q1 CO2 Update", resourceUid: "c1", dateTime: "2025-01", content: "Carbon up." },
  { id: "p2", title: "Energy Consumption Analysis for January — Detailed Breakdown by Source and Department", resourceUid: "c2", dateTime: "2025-01", content: "This month we observed a significant increase in electricity consumption across all departments, particularly in manufacturing and logistics. Key drivers include expanded production lines and colder temperatures increasing heating demands. Immediate action is recommended." },
  { id: "p3", title: "Feb Carbon Review", resourceUid: "c3", dateTime: "2025-02", content: "Emissions slightly down from last month." },
  { id: "p4", title: "Green Initiative Progress Report — Renewable Energy Transition and Scope 2 Reduction Strategy for Q1 2025", resourceUid: "c4", dateTime: "2025-02", content: "Our renewable energy transition is progressing steadily. Solar panel installations at the main facility are now 70% complete, and wind energy contracts have been finalized with two regional providers. Projected scope 2 reductions of 18% are expected by end of Q2." },
  { id: "p5", title: "Scope 2 Reduction Plan", resourceUid: "c1", dateTime: "2025-03", content: "New procurement strategy in place." },
  { id: "p6", title: "Comprehensive Waste Management and Recycling Performance Report for the First Quarter of 2025", resourceUid: "c2", dateTime: "2025-03", content: "Q1 waste metrics show a 12% reduction in landfill contributions compared to the same period last year. Recycling rates improved across all sites." },
  { id: "p7", title: "Water Usage Analysis", resourceUid: "c3", dateTime: "2025-04", content: "Water usage exceeded targets in April due to increased cooling system demand during unseasonably warm conditions. A revised usage policy has been drafted and is pending approval from facility managers and the sustainability committee." },
  { id: "p8", title: "April Supply Chain Emissions", resourceUid: "c4", dateTime: "2025-04", content: "Scope 3 up 5%." },
 { id: "p9", title: "Renewable Energy Adoption Update — Solar, Wind, and Grid Decarbonization Progress Across All Facilities", resourceUid: "c1", dateTime: "2025-05", content: "As of May 2025, renewable energy sources now account for 43% of total energy consumption across all facilities, marking a significant milestone in our long-term decarbonization roadmap. This represents a 14 percentage point increase compared to the same period last year, driven primarily by the successful commissioning of three new solar installations and the activation of two wind energy procurement contracts.\n\nThe largest contributor to this growth has been the rooftop solar expansion at our main manufacturing facility, which reached full operational capacity in late April. The system, comprising over 2,400 photovoltaic panels, is expected to generate approximately 1.8 GWh of clean electricity annually, offsetting an estimated 900 tonnes of CO2 equivalent per year. In parallel, our secondary logistics hub completed installation of a 400kW ground-mounted solar array, which now covers roughly 60% of that site's daytime energy needs.\n\nOn the wind energy front, long-term power purchase agreements signed in Q4 2024 with two regional wind farm operators have begun delivering results. Under these agreements, we receive certified renewable electricity credits alongside guaranteed supply at fixed rates through 2031, providing both environmental and financial predictability.\n\nLooking ahead to H2 2025, we are on track to reach our internal target of 50% renewable energy share by year-end. Key upcoming initiatives include battery storage pilot programs at two sites, a feasibility study for on-site wind turbine installation, and expanded green tariff procurement for facilities where on-site generation is not practical. The sustainability team will publish a full mid-year energy transition report in July." },
  { id: "p10", title: "ESG Summary", resourceUid: "c2", dateTime: "2025-05", content: "This quarter's ESG performance reflects strong environmental gains offset by moderate social score improvements. Governance metrics remain stable. Full board review is scheduled for June, with a focus on aligning targets with updated international sustainability frameworks and stakeholder expectations." },
  { id: "p11", title: "Carbon Offset Report", resourceUid: "c3", dateTime: "2025-06", content: "Purchased 500 carbon credits." },
  { id: "p12", title: "Mid-Year Sustainability Goals Review — Progress, Gaps, and Revised Targets for H2 2025", resourceUid: "c4", dateTime: "2025-06", content: "Six of nine sustainability targets are on track. Three require revised timelines due to supply chain delays and regulatory changes in key operating regions." },
];